version: '3'

services:
  mysql:
    build: .
    image: servercontainers/mysql
    restart: always
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: password
      BACKUP_ENABLED: enable
      DB_NAME: exampledb
      DB_USER: exampleuser
      DB_PASSWORD: examplepassword
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/backup:/var/mysql-backup
    ports:
      - 3306:3306
    networks:
      - mysql-test

  phpmyadmin:
    image: marvambass/phpmyadmin
    restart: always
    environment:
      PHPMYADMIN_MYSQL_HOST: mysql
    ports:
      - 443:443
    networks:
      - mysql-test

networks:
  mysql-test:
    driver: bridge
